#  ------- Required to allow pushing data/ assets generated by Playwright to an Azure Storage Account -------- #
resource "azuread_application" "playwright_reporter" {
  display_name     = "adminservicestest-k6tests-playwrightreporter"
  sign_in_audience = "AzureADMyOrg"
}

resource "azuread_service_principal" "playwright_reporter" {
  client_id = azuread_application.playwright_reporter.client_id
}

resource "azuread_application_federated_identity_credential" "playwright_reporter" {
  application_id = azuread_application.playwright_reporter.id
  display_name   = "adminservicestest-k6tests-playwrightreporter"
  audiences      = ["api://AzureADTokenExchange"]
  issuer         = azurerm_kubernetes_cluster.k6tests.oidc_issuer_url
  subject        = "system:serviceaccount:platform:playwright-reporter-sa"
}

data "azurerm_storage_account" "playwrightartifacts" {
  provider            = azurerm.platform_dev
  name                = "playwrightartifacts6546"
  resource_group_name = "playwright-rg"
}

data "azurerm_storage_container" "playwrightartifacts" {
  provider           = azurerm.platform_dev
  name               = "playwright-artifacts"
  storage_account_id = data.azurerm_storage_account.playwrightartifacts.id
}

resource "azurerm_role_assignment" "storage_blob_data_writer" {
  scope                = data.azurerm_storage_container.playwrightartifacts.id
  role_definition_name = "Storage Blob Data Writer"
  principal_id         = azuread_service_principal.playwright_reporter.object_id
}

resource "kubernetes_service_account_v1" "playwright_reporter" {
  metadata {
    name      = "playwright-reporter-sa"
    namespace = "platform"
    annotations = {
      "azure.workload.identity/client-id" : azuread_application.playwright_reporter.client_id
    }
  }
}

# ------------------------------------------------------------------------------------------------------------ #
