apiVersion: batch/v1
kind: CronJob
metadata:
  name: helm-uninstall-outdated-apps
spec:
  # schedule: "8 8 * * 1,2,3,4"  # At 08:08 on Monday, Tuesday, Wednesday, and Thursday
  schedule: "8 8 * * 1,2,3,4"
  timeZone: "Europe/Oslo"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: helm-uninstall-outdated-apps
          containers:
            - name: helm-uninstall-outdated-apps
              image: altinncr.azurecr.io/docker.io/alpine/helm:3
              command: ["/bin/sh", "-c"]
              args:
                - |
                  # To debug uncomment following line
                  # set -x
                  apk add --no-cache jq coreutils curl;
                  # Load whitelist from the ConfigMap
                  WHITELIST=$(cat /config/whitelist | tr '\n' ' ');
                  # Script to uninstall outdated helm releases
                  CUTOFF_DATE=$(date -d '3 months ago' +%s);
                  RELEASES=$(helm list --all --output json);
                  echo "$RELEASES" | jq -c '.[]' | while read release; do
                      RELEASE_NAME=$(echo "$release" | jq -r '.name');
                      # Skip uninstall if the release is in the whitelist
                      if echo " $WHITELIST " | grep -q " $RELEASE_NAME "; then
                          echo "Skipping Helm release: $RELEASE_NAME (Whitelisted)";
                          continue;
                      fi
                      # Remove the fractional seconds and ' +0000 UTC' part from the timestamp
                      UPDATED_TIME=$(echo "$release" | jq -r '.updated' | sed -E 's/\.[0-9]+.*//' | xargs -I {} date -d {} +%s);
                      if [ "$UPDATED_TIME" -lt "$CUTOFF_DATE" ]; then
                          echo "Uninstalling Helm release: $RELEASE_NAME (Last updated more than 3 months ago)";
                          helm uninstall "$RELEASE_NAME"; # To debug add --debug before ;
                      fi;
                  done
              volumeMounts:
                - name: config-volume
                  mountPath: /config
                  readOnly: true
          volumes:
            - name: config-volume
              configMap:
                name: helm-uninstall-whitelist
          restartPolicy: OnFailure
      ttlSecondsAfterFinished: 0
      backoffLimit: 3
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
