apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm-uninstall-outdated-apps
  namespace: default
rules:
  - apiGroups: [""]
    resources:
      [
        "pods",
        "services",
        "secrets",
        "configmaps",
        "persistentvolumeclaims",
        "serviceaccounts",
      ]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["traefik.containo.us"]
    resources: ["ingressroutes", "middlewares"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes", "middlewares"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "watch", "delete"]
