//go:build !ignore_autogenerated

/*
Copyright 2025 Altinn.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationIdentity) DeepCopyInto(out *ApplicationIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationIdentity.
func (in *ApplicationIdentity) DeepCopy() *ApplicationIdentity {
	if in == nil {
		return nil
	}
	out := new(ApplicationIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationIdentityList) DeepCopyInto(out *ApplicationIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationIdentityList.
func (in *ApplicationIdentityList) DeepCopy() *ApplicationIdentityList {
	if in == nil {
		return nil
	}
	out := new(ApplicationIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationIdentitySpec) DeepCopyInto(out *ApplicationIdentitySpec) {
	*out = *in
	if in.AzureAudiences != nil {
		in, out := &in.AzureAudiences, &out.AzureAudiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationIdentitySpec.
func (in *ApplicationIdentitySpec) DeepCopy() *ApplicationIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationIdentityStatus) DeepCopyInto(out *ApplicationIdentityStatus) {
	*out = *in
<<<<<<< HEAD
=======
	if in.AzureAudiences != nil {
		in, out := &in.AzureAudiences, &out.AzureAudiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
>>>>>>> tmp-original-19-11-25-19-36
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
<<<<<<< HEAD
=======
	if in.PrincipalID != nil {
		in, out := &in.PrincipalID, &out.PrincipalID
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.ManagedIdentityName != nil {
		in, out := &in.ManagedIdentityName, &out.ManagedIdentityName
		*out = new(string)
		**out = **in
	}
>>>>>>> tmp-original-19-11-25-19-36
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationIdentityStatus.
func (in *ApplicationIdentityStatus) DeepCopy() *ApplicationIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationIdentityStatus)
	in.DeepCopyInto(out)
	return out
}
