prometheus_rw_server_url: http://kube-prometheus-stack-prometheus.monitoring:9090/api/v1/write
node_types:
  spot:
    nodeSelector:
      - label: "kubernetes.azure.com/scalesetpriority"
        value: "spot"
      - label: spot
        value: true
    tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
  spot8cpu28gbmem:
    nodeSelector:
      - label: "kubernetes.azure.com/scalesetpriority"
        value: "spot"
      - label: spot8cpu28gbmem
        value: true
    tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
  default:
    nodeSelector: []
    tolerations: []
