admin:
  github:
    owner: Altinn
    repository: altinn-platform

products:
  - name: Platform
    slug: PAP # Product Altinn Platform
    github:
      owner: altinn
      repositories:
        - altinn-platform
        - terraform-azurerm-altinn-modules

  - name: Authorization
    slug: PAA # Product Altinn Authorization
    github:
      owner: Altinn
      repositories:
        - altinn-access-management
        - altinn-authentication
        - altinn-authorization
        - altinn-authorization-tmp

  - name: Studio
    slug: PAS # Product Altinn Studio
    github:
      owner: Altinn
      repositories:
        - altinn-studio

  - name: Dialogporten
    slug: DDP # Product DigDir Dialogporten
    github:
      owner: Altinn
      repositories:
        - dialogporten
        - dialogporten-frontend

  - name: Core
    slug: PAC # Product Altinn Core
    github:
      owner: Altinn
      repositories:
        - altinn-receipt
        - altinn-notifications

  - name: Apps
    slug: APP # Apps
    github:
      owner: altinn
      repositories:
        - app-frontend-react

  - name: Digitalt Dødsbo
    slug: DDD # DigDir Digitalt Dodsbo
    github:
      owner: Altinn
      repositories:
        - dd-infrastructure
