FROM k6-action-image:test
COPY --from=golang:1.26-alpine@sha256:2389ebfa5b7f43eeafbd6be0c3700cc46690ef842ad962f6c5bd6be49ed82039 /usr/local/go/ /usr/local/go/
ENV PATH="/usr/local/go/bin:${PATH}"

COPY actions/generate-k6-manifests /actions/generate-k6-manifests
WORKDIR /actions/generate-k6-manifests
RUN go mod download
RUN go test -v ./...
