FROM k6-action-image:test
COPY --from=golang:1.26-alpine@sha256:3ad57304ad93bbec8548a0437ad9e06a455660655d9af011d58b993f6f615648 /usr/local/go/ /usr/local/go/
ENV PATH="/usr/local/go/bin:${PATH}"

COPY actions/generate-k6-manifests /actions/generate-k6-manifests
WORKDIR /actions/generate-k6-manifests
RUN go mod download
RUN go test -v ./...
