FROM k6-action-image:test
COPY --from=golang:1.26-alpine@sha256:91eda9776261207ea25fd06b5b7fed8d397dd2c0a283e77f2ab6e91bfa71079d /usr/local/go/ /usr/local/go/
ENV PATH="/usr/local/go/bin:${PATH}"

COPY actions/generate-k6-manifests /actions/generate-k6-manifests
WORKDIR /actions/generate-k6-manifests
RUN go mod download
RUN go test -v ./...
