apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dis-otel-operator
  namespace: monitoring
spec:
  interval: 1h
  timeout: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  chart:
    spec:
      chart: opentelemetry-operator
      sourceRef:
        kind: HelmRepository
        name: otel-oci
        namespace: monitoring
      # renovate: datasource=helm registryUrl=https://open-telemetry.github.io/opentelemetry-helm-charts packageName=opentelemetry-operator
      version: 0.102.0
  values:
    manager:
      image:
        repository: altinncr.azurecr.io/ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
      collectorImage:
        repository: altinncr.azurecr.io/ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s
      serviceMonitor:
        enabled: false
      env:
        ENABLE_WEBHOOKS: "false"
      podAnnotations:
        linkerd.io/inject: "enabled"
        config.linkerd.io/skip-outbound-ports: "443"
    admissionWebhooks:
      create: false
