# renovate: datasource=docker packageName=ghcr.io/altinn/altinn-platform/azure-devops-agent
FROM ghcr.io/altinn/altinn-platform/azure-devops-agent:v1.2.7@sha256:903dc06a1f174332f97d33e5297328e7b281a98bc0b4ffb7d31d9f3bdaea5c34
COPY scripts/install.sh .
RUN ./install.sh
