apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default
  - applicationidentities.yaml
  - serviceaccounts.yaml

patches:
  - path: manager_kind_patch.yaml
    target:
      kind: Deployment
      name: dis-vault-operator-controller-manager
      namespace: dis-vault-operator-system
