apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: azure-service-operator
  namespace: azureserviceoperator-system
spec:
  interval: 1h
  targetNamespace: azureserviceoperator-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  install:
    createNamespace: true
  chart:
    spec:
      chart: azure-service-operator
      # renovate: datasource=helm registryUrl=https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts packageName=azure-service-operator
      version: "v2.17.0"
      sourceRef:
        kind: HelmRepository
        name: aso2
        namespace: azureserviceoperator-system
  values:
    crdPattern: ${CRD_PATTERN}
    createAzureOperatorSecret: true
    azureTenantID: ${AZURE_TENANT_ID}
    azureClientID: ${AZURE_CLIENT_ID}
    azureSubscriptionID: ${AZURE_SUBSCRIPTION_ID}
    useWorkloadIdentityAuth: true
    serviceAccount:
      name: "azureserviceoperator-system"
