apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aso2
  namespace: azureserviceoperator-system
spec:
  interval: 15m
  url: https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts