apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      # renovate: datasource=helm registryUrl=https://prometheus-community.github.io/helm-charts packageName=prometheus-blackbox-exporter
      version: 11.5.0
  interval: 1h
  timeout: 15m
  install:
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ServiceMonitor
              group: monitoring.coreos.com
            patch: |-
              - op: replace
                path: /apiVersion
                value: azmonitoring.coreos.com/v1
              - op: add
                path: /spec/labelLimit
                value: 63
              - op: add
                path: /spec/labelNameLengthLimit
                value: 511
              - op: add
                path: /spec/labelValueLengthLimit
                value: 1023
          - target:
              kind: PodMonitor
              group: monitoring.coreos.com
            patch: |-
              - op: replace
                path: /apiVersion
                value: azmonitoring.coreos.com/v1
              - op: add
                path: /spec/labelLimit
                value: 63
              - op: add
                path: /spec/labelNameLengthLimit
                value: 511
              - op: add
                path: /spec/labelValueLengthLimit
                value: 1023
  targetNamespace: monitoring
  values:
    image:
      registry: altinncr.azurecr.io/quay.io
    serviceMonitor:
      enabled: true
      targets: []
