apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      version: 0.16.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
  interval: 1h
  timeout: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    installCRDs: true
    # we run the controller **without** Azure identity;
    # actual auth is delegated via SecretStore.serviceAccountRef
    serviceAccount:
      create: false
