apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/external-secrets/charts
