name: "Azure Grafana Token Setup"
description: "Logs in to Azure and retrieves a Grafana access token."
inputs:
  arm_client_id:
    required: true
    description: Federated Azure Client ID.
  arm_subscription_id:
    required: true
    description: Azure Subscription ID
  arm_tenant_id:
    description: Azure Tenant ID
    default: cd0026d8-283b-4a55-9bfa-d0ef4a8ba21c

runs:
  using: "composite"
  steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        allow-no-subscriptions: true

    - name: Get Azure Grafana Access Token
      shell: bash
      run: |
        token=$(az account get-access-token --resource ${{ inputs.resource-id }} --query accessToken -o tsv)
        if [ -z "$token" ]; then
          echo "Failed to retrieve Grafana access token" >&2
          exit 1
        fi
        echo "::add-mask::$token"
        echo "TF_VAR_grafana_access_token=$token" >> $GITHUB_ENV
