apiVersion: apps/v1
kind: Deployment
metadata:
  name: dis-console
  namespace: product-dis
  labels:
    app: dis-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dis-console
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: dis-console
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: dis-console
      automountServiceAccountToken: true
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: dis-console
          image: ghcr.io/altinn/altinn-platform/dis-console:v1.6.0
          args:
            - server
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DB_URI
              valueFrom:
                configMapKeyRef:
                  name: dis-console-central-dis-console-dis-pgsql
                  key: uri
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: dis-console
  namespace: product-dis
  labels:
    app: dis-console
spec:
  selector:
    app: dis-console
  ports:
    - name: http
      port: 80
      targetPort: http
