apiVersion: apps/v1
kind: Deployment
metadata:
  name: dis-console-ui
  namespace: product-dis
  labels:
    app: dis-console-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dis-console-ui
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: dis-console-ui
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: dis-console-ui
          image: ghcr.io/altinn/altinn-platform/dis-console-ui:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: DIS_CONSOLE_API
              value: http://dis-console
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: dis-console-ui
  namespace: product-dis
  labels:
    app: dis-console-ui
spec:
  type: ClusterIP
  selector:
    app: dis-console-ui
  ports:
    - name: http
      port: 80
      targetPort: http
