apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dis-console-flux-reader
rules:
  - apiGroups:
      - kustomize.toolkit.fluxcd.io
    resources:
      - kustomizations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - helm.toolkit.fluxcd.io
    resources:
      - helmreleases
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - ocirepositories
      - helmrepositories
      - helmcharts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.dis.altinn.cloud
    resources:
      - databaseservers
      - databases
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - vault.dis.altinn.cloud
    resources:
      - vaults
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - application.dis.altinn.cloud
    resources:
      - applicationidentities
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apim.dis.altinn.cloud
    resources:
      - apis
      - apiversions
      - backends
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dis-console-flux-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dis-console-flux-reader
subjects:
  - kind: ServiceAccount
    name: dis-console-agent
    namespace: product-dis
