apiVersion: storage.dis.altinn.cloud/v1alpha1
kind: DatabaseServer
metadata:
  name: dis-console-central
  namespace: product-dis
spec:
  version: 17
  serverType: dev
  auth:
    admin:
      identity:
        identityRef:
          name: dis-console-db-admin
