apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - dis-console-db-admin.yaml
  - dis-console.yaml
  - dis-console-databaseserver.yaml
  - dis-console-database.yaml
  - dis-console-deployment.yaml
