apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: otel-azure-kv-store
  namespace: monitoring
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: ${KV_URI}
      serviceAccountRef:
        name: otel-collector
        namespace: monitoring
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-insights-connstring-external-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: otel-azure-kv-store
  target:
    name: app-insights-connstring
    creationPolicy: Owner
  data:
    - secretKey: connectionString           # key inside the k8s Secret
      remoteRef:
        key: connectionString
