namespace: platform
test_definitions:
    - test_file: actions/generate-k6-manifests/test_service/k8s_wrapper/get_deployments.js
      config_file: ""
      env_file: ""
      contexts:
        - environment: at22
          node_type: spot
          test_type:
            type: spike
            enabled: true
            config_file: ""
          test_run:
            name: get-deployments
            parallelism: 1
            resources:
                requests:
                    memory: 200Mi
                    cpu: 250m
            env: []
            secrets: []
