apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dis-identity-operator
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./default
  postBuild:
    substitute:
      DISID_ISSUER_URL: ${DISID_ISSUER_URL}
      DISID_TARGET_RESOURCE_GROUP: ${DISID_TARGET_RESOURCE_GROUP}
  prune: false
  retryInterval: 5m0s
  images:
    - name: controller
      newName: altinncr.azurecr.io/ghcr.io/altinn/altinn-platform/dis-identity-operator
      newTag: v0.0.4
  sourceRef:
    kind: OCIRepository
    name: dis-identity-operator
    namespace: flux-system
  targetNamespace: dis-identity-operator-system
  timeout: 5m0s
  wait: true
