name: Toil
description: Create a none user-story issue (chore, tech issue, backend issue).
labels: ["kind/chore", "kind/toil", "status/triage"]
projects: Altinn/177
body:
  - type: markdown
    attributes:
      value: |
        Evaluate if this can be automated to remove the future need for this kind of toil. If so create a Enhancement issue
  - type: dropdown
    id: type
    attributes:
      label: Toil type
      options:
        - "[Terraform upgrades Apps](https://pedia.altinn.cloud/altinn-3/ops/patching/terraform/apps)"
        - "[Terraform upgrades Platform](https://pedia.altinn.cloud/altinn-3/ops/patching/terraform/platform)"
        - "Other"
  - type: textarea
    id: Context
    attributes:
      label: Context for the task
      description: If this issue/task needs more information or other option was chosen, please give some more context
