name: Add tag to existing flux OCI image
description: 'Re-tag an existing OCI image in Azure Container Registry (ACR) using the FluxCLI'

inputs:
  image_name:
    description: 'Name of the OCI image to tag'
    required: true
  from_tag:
    description: 'The tag of the existing image to re-tag'
    required: true
  tag:
    description: 'The new tag to apply to the existing image'
    required: true
    type: string@
  workdir:
    description: 'Folder containing the OCI resources'
    required: true
    type: string
  acr_name:
    description: 'Name of the Azure Container Registry (ACR) to use'
    required: false
    default: 'altinncr'
    type: string
secrets:
  azure_app_id:
    description: 'Azure application id used to authenticate to altinncr'
    required: true
  azure_subscription_id:
    description: 'Azure subscription id used to authenticate to altinncr'
    required: true
  azure_tenant_id:
    description: 'Azure tenant id used to authenticate to altinncr'
    required: true



runs:
  using: composite
  defaults:
    run:
      working-directory: ${{ inputs.workdir }}
  steps:
    - name: Prepare Job for Pushing Flux OCI Artifacts to Azure Container Registry
      uses: Altinn/altinn-platform/actions/flux/setup-flux-acr@main
      id: setup_flux_acr
      with:
        acr_name: ${{ inputs.acr_name }}
    - name: Tag release artifact
      env:
        ARTIFACT_NAME: ${{ inputs.image_name }}
        FROM_TAG: ${{ inputs.from_tag }}
        TO_TAG: ${{ inputs.tag }}
      run: |
        creds=${{ steps.setup_flux_acr.outputs.acr_token }}
        container_registry=${{ inputs.acr_name }}.azurecr.io
        flux tag artifact "oci://${container_registry}/${ARTIFACT_NAME}:${FROM_TAG} \
            --provider=azure \
            --tag "${TO_TAG}" \
            --creds="${creds}"
