name: Add tag to existing flux OCI image
description: "Re-tag an existing OCI image in Azure Container Registry (ACR) using the FluxCLI"

inputs:
  image_name:
    description: "Name of the OCI image to tag"
    required: true
    type: string
  from_tag:
    description: "The tag of the existing image to re-tag"
    required: true
    type: string
  tag:
    description: "The new tag to apply to the existing image"
    required: true
    type: string
  workdir:
    description: "Folder containing the OCI resources"
    required: true
    type: string
  acr_name:
    description: "Name of the Azure Container Registry (ACR) to use"
    required: false
    default: "altinncr"
    type: string
    pattern: "^[a-zA-Z0-9-]{5,50}$"
  azure_app_id:
    description: "Azure application id used to authenticate to altinncr"
    required: true
  azure_subscription_id:
    description: "Azure subscription id used to authenticate to altinncr"
    required: true
  azure_tenant_id:
    description: "Azure tenant id used to authenticate to altinncr"
    required: true

runs:
  using: composite
  steps:
    - name: Prepare Job for Pushing Flux OCI Artifacts to Azure Container Registry
      uses: ./actions/flux/setup-flux-acr
      id: setup_flux_acr
      with:
        azure_app_id: ${{ inputs.azure_app_id }}
        azure_subscription_id: ${{ inputs.azure_subscription_id }}
        azure_tenant_id: ${{ inputs.azure_tenant_id }}
    - name: Tag release artifact
      env:
        ARTIFACT_NAME: ${{ inputs.image_name }}
        FROM_TAG: ${{ inputs.from_tag }}
        TO_TAG: ${{ inputs.tag }}
        ACR_NAME: ${{ inputs.acr_name }}
      shell: bash
      run: |
        container_registry=${ACR_NAME}.azurecr.io
        credentials=$(az acr login --name ${ACR_NAME} --expose-token)
        flux tag artifact "oci://${container_registry}/${ARTIFACT_NAME}:${FROM_TAG}" \
            --provider=azure \
            --tag "${TO_TAG}" \
            --creds="${credentials}"
