apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: monitoring
spec:
  env:
    - name: APPLICATIONINSIGHTS_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: app-insights-connstring
          key: connectionString
  image: otel/opentelemetry-collector-contrib:0.122.0
  podAnnotations:
    linkerd.io/inject: "enabled"
    config.linkerd.io/skip-outbound-ports: "443"
  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 256Mi
  mode: deployment
  upgradeStrategy: automatic
  serviceAccount: otel-collector
  observability:
    metrics:
      disablePrometheusAnnotations: true
      enableMetrics: true
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch: {}
      probabilistic_sampler:
        # We should decrease this later as more apps use
        # the collector
        sampling_percentage: 50
    exporters:
      azuremonitor: {}
      debug: {}

    service:
      telemetry:
        metrics:
          level: basic
          readers:
          - pull:
              exporter:
                prometheus:
                  host: 0.0.0.0
                  port: 8888
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [azuremonitor, debug]
        traces:
          receivers: [otlp]
          processors: [probabilistic_sampler, batch]
          exporters: [azuremonitor, debug]