apiVersion: redis.dis.altinn.cloud/v1alpha1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: dis-redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redis-service-account-sample
spec:
  serviceAccountRef:
    name: redis-owner-sa
  sku: Balanced_B0
  highAvailability: true
  clientProtocol: Encrypted
  evictionPolicy: NoEviction
  tags:
    app: service-account-sample
    env: dev
