apiVersion: redis.dis.altinn.cloud/v1alpha1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: dis-redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redis-sample
spec:
  identityRef:
    name: app-identity-sample
  sku: Balanced_B0
  highAvailability: true
  clientProtocol: Encrypted
  evictionPolicy: NoEviction
  tags:
    app: sample
    env: dev
