apiVersion: application.dis.altinn.cloud/v1alpha1
kind: ApplicationIdentity
metadata:
  labels:
    app.kubernetes.io/name: dis-identity-operator
    app.kubernetes.io/managed-by: kustomize
  name: applicationidentity-sample
spec:
  # TODO(user): Add fields here
