# This patch adds an Azure Workload Identity required annotation
# to the service account with the application client ID
- op: add
  path: /metadata/annotations
  value:
    azure.workload.identity/client-id: "" # TODO: Should be populated based on the output from Terraform
