apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dis-otel-operator
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: opentelemetry-operator
      sourceRef:
        kind: HelmRepository
        name: otel-oci
        namespace: monitoring
  values:
    manager:
      image:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
        tag: "0.120.0"
      serviceMonitor:
        enabled: false
      env:
        ENABLE_WEBHOOKS: "false"
      podAnnotations:
        linkerd.io/inject: "enabled"
        config.linkerd.io/skip-outbound-ports: "443"
    admissionWebhooks:
      create: false