name: Terraform Plan
description: Run terraform plan
inputs:
  working_directory:
    description: The directory where the Terraform project is located.
    default: ./infrastructure
    required: true

  arm_client_id:
    required: true
    description: Federated Azure Client ID.
  arm_subscription_id:
    required: true
    description: Azure Subscription ID
  arm_tenant_id:
    description: Azure Tenant ID
    default: cd0026d8-283b-4a55-9bfa-d0ef4a8ba21c

  tf_args:
    description: Terraform arguments
    required: false
  tf_output_file:
    description: JSON file for dumping tf state output
    default: tf_output.json

runs:
  using: composite
  steps:
    - name: Artifact Key
      id: artifact_key
      shell: bash
      run: |
        TF_STATE_FILE=${{ env.TF_STATE_FILE }}
        ARTIFACT_KEY="${TF_STATE_FILE////_}.tfplan"
        echo "ARTIFACT_KEY=$ARTIFACT_KEY" >> $GITHUB_ENV

    - name: Download Plan
      id: artifact
      uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
      with:
        name: ${{ env.ARTIFACT_KEY }}
        path: ${{ inputs.working_directory }}

    - name: Terraform Apply
      id: apply
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        terraform apply -input=false -auto-approve ${{ inputs.tf_args }} tfplan.out
        terraform output -json >> ${{ inputs.tf_output_file }}
      env:
        ARM_CLIENT_ID: ${{ inputs.arm_client_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.arm_subscription_id }}
        ARM_TENANT_ID: ${{ inputs.arm_tenant_id }}
        ARM_USE_OIDC: "true"
