name: Terraform Plan
description: Run terraform plan
inputs:
  working_directory:
    description: The directory where the Terraform project is located.
    default: ./infrastructure
    required: true

  arm_client_id:
    required: true
    description: Federated Azure Client ID.
  arm_subscription_id:
    required: true
    description: Azure Subscription ID
  arm_tenant_id:
    description: Azure Tenant ID
    default: cd0026d8-283b-4a55-9bfa-d0ef4a8ba21c

  tf_args:
    description: Terraform arguments
    required: false
  tf_output_file:
    description: JSON file for dumping tf state output
    default: tf_output.json

runs:
  using: composite
  steps:
    - name: Artifact Key
      id: artifact_key
      shell: bash
      env:
        TERRAFORM_STATE_FILE: ${{ env.TF_STATE_FILE }}
      run: |
        TF_STATE_FILE=$TERRAFORM_STATE_FILE
        ARTIFACT_KEY="${TF_STATE_FILE////_}.tfplan"
        echo "ARTIFACT_KEY=$ARTIFACT_KEY" >> $GITHUB_ENV

    - name: Download Plan
      id: artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: ${{ env.ARTIFACT_KEY }}
        path: ${{ inputs.working_directory }}

    - name: Terraform Apply
      id: apply
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        terraform apply -input=false -auto-approve $TERRAFORM_ARGS tfplan.out
        terraform output -json >> $TERRAFORM_OUTPUT_FILE
      env:
        ARM_CLIENT_ID: ${{ inputs.arm_client_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.arm_subscription_id }}
        ARM_TENANT_ID: ${{ inputs.arm_tenant_id }}
        ARM_USE_OIDC: "true"
        TERRAFORM_OUTPUT_FILE: ${{ inputs.tf_output_file }}
        TERRAFORM_ARGS: ${{ inputs.tf_args }}
