---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.dis.altinn.cloud
  resources:
  - applicationidentities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.azure.com
  resources:
  - redisenterprises
  - redisenterprisesdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.azure.com
  resources:
  - redisenterprises/status
  - redisenterprisesdatabases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - network.azure.com
  resources:
  - privateendpoints
  - privatednszones
  - privatednszonesvirtualnetworklinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.azure.com
  resources:
  - privateendpoints/status
  - privatednszones/status
  - privatednszonesvirtualnetworklinks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - redis.dis.altinn.cloud
  resources:
  - redises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.dis.altinn.cloud
  resources:
  - redises/status
  verbs:
  - get
  - patch
  - update
