apiVersion: apim.dis.altinn.cloud/v1alpha1
kind: ApiVersion
metadata:
  labels:
    app.kubernetes.io/name: dis-apim-operator
    app.kubernetes.io/managed-by: kustomize
  name: apiversion-sample
spec:
  # TODO(user): Add fields here
