apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - target:
      kind: Vault
      name: dis-sample-vault
    patch: |-
      - op: add
        path: /spec/groupObjectId
        value: 4445ace5-cc1c-401a-b02c-1af094ee2cb1
      - op: add
        path: /spec/tags/env
        value: at22
