# This rule is not used by the project dis-identity-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to application.dis.altinn.cloud resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dis-identity-operator
    app.kubernetes.io/managed-by: kustomize
  name: applicationidentity-viewer-role
rules:
- apiGroups:
  - application.dis.altinn.cloud
  resources:
  - applicationidentities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.dis.altinn.cloud
  resources:
  - applicationidentities/status
  verbs:
  - get
