---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - application.dis.altinn.cloud
  resources:
  - applicationidentities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.dis.altinn.cloud
  resources:
  - applicationidentities/finalizers
  verbs:
  - update
- apiGroups:
  - application.dis.altinn.cloud
  resources:
  - applicationidentities/status
  verbs:
  - get
  - patch
  - update
