name: Terraform Plan
description: Run terraform plan
inputs:
  working_directory:
    description: The directory where the Terraform project is located.
    default: ./infrastructure
    required: true

  arm_client_id:
    required: true
    description: Federated Azure Client ID.
  arm_subscription_id:
    required: true
    description: Azure Subscription ID
  arm_tenant_id:
    description: Azure Tenant ID
    default: cd0026d8-283b-4a55-9bfa-d0ef4a8ba21c

  tf_args:
    description: Terraform arguments
    required: false

outputs:
  plan_step_exitcode:
    description: "steps.plan.outputs.exitcode"
    value: ${{ steps.plan.outputs.exitcode }}
  plan_step_outcome:
    description: "steps.plan.outcome"
    value: ${{ steps.plan.outcome }}

runs:
  using: composite
  steps:
    - name: Terraform Plan
      id: plan
      shell: bash
      if: always()
      working-directory: ${{ inputs.working_directory }}
      run: |
        terraform plan -detailed-exitcode -no-color -input=false -out tfplan.out ${{ inputs.tf_args }} 2>&1 > tfplan.log  && cat tfplan.log || export EC=$?; cat tfplan.log; exit $EC
      env:
        ARM_CLIENT_ID: ${{ inputs.arm_client_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.arm_subscription_id }}
        ARM_TENANT_ID: ${{ inputs.arm_tenant_id }}
        ARM_USE_OIDC: "true"

    - name: Artifact Key
      id: artifact_key
      shell: bash
      run: |
        TF_STATE_FILE=${{ env.TF_STATE_FILE }}
        ARTIFACT_KEY="${TF_STATE_FILE////_}.tfplan"
        echo "ARTIFACT_KEY=$ARTIFACT_KEY" >> $GITHUB_ENV

    - name: Upload Plan
      id: artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: success()
      with:
        name: ${{ env.ARTIFACT_KEY }}
        path: ${{ inputs.working_directory }}/tfplan.out
