apiVersion: vault.dis.altinn.cloud/v1alpha1
kind: Vault
metadata:
  labels:
    app.kubernetes.io/name: dis-vault-operator
    app.kubernetes.io/managed-by: kustomize
  name: vault-service-account-sample
spec:
  serviceAccountRef:
    name: vault-owner-sa
  externalSecrets: true
  sku: standard
  publicNetworkAccess: Enabled
  softDeleteRetentionDays: 90
  purgeProtectionEnabled: true
  tags:
    app: service-account-sample
    env: dev
