apiVersion: vault.dis.altinn.cloud/v1alpha1
kind: Vault
metadata:
  labels:
    app.kubernetes.io/name: dis-vault-operator
    app.kubernetes.io/managed-by: kustomize
  name: vault-es-sample
spec:
  identityRef:
    name: app-identity-sample
  externalSecrets: true
  sku: standard
  publicNetworkAccess: Enabled
  softDeleteRetentionDays: 90
  purgeProtectionEnabled: true
  tags:
    app: external-secrets-sample
    env: dev
