//go:build !ignore_autogenerated

<<<<<<< HEAD
=======
/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

>>>>>>> tmp-original-26-05-26-00-39
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminIdentitySpec) DeepCopyInto(out *AdminIdentitySpec) {
	*out = *in
	in.Identity.DeepCopyInto(&out.Identity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminIdentitySpec.
func (in *AdminIdentitySpec) DeepCopy() *AdminIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(AdminIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationIdentityRef) DeepCopyInto(out *ApplicationIdentityRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationIdentityRef.
func (in *ApplicationIdentityRef) DeepCopy() *ApplicationIdentityRef {
	if in == nil {
		return nil
	}
	out := new(ApplicationIdentityRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Database) DeepCopyInto(out *Database) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Database.
func (in *Database) DeepCopy() *Database {
	if in == nil {
		return nil
	}
	out := new(Database)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Database) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseAccessSpec) DeepCopyInto(out *DatabaseAccessSpec) {
	*out = *in
	out.App = in.App
	out.Owner = in.Owner
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseAccessSpec.
func (in *DatabaseAccessSpec) DeepCopy() *DatabaseAccessSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseList) DeepCopyInto(out *DatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Database, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseList.
func (in *DatabaseList) DeepCopy() *DatabaseList {
	if in == nil {
		return nil
	}
	out := new(DatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabasePrincipalSpec) DeepCopyInto(out *DatabasePrincipalSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabasePrincipalSpec.
func (in *DatabasePrincipalSpec) DeepCopy() *DatabasePrincipalSpec {
	if in == nil {
		return nil
	}
	out := new(DatabasePrincipalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseServer) DeepCopyInto(out *DatabaseServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseServer.
func (in *DatabaseServer) DeepCopy() *DatabaseServer {
	if in == nil {
		return nil
	}
	out := new(DatabaseServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseServerAuth) DeepCopyInto(out *DatabaseServerAuth) {
	*out = *in
	in.Admin.DeepCopyInto(&out.Admin)
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(UserIdentitySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseServerAuth.
func (in *DatabaseServerAuth) DeepCopy() *DatabaseServerAuth {
	if in == nil {
		return nil
	}
	out := new(DatabaseServerAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseServerList) DeepCopyInto(out *DatabaseServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseServerList.
func (in *DatabaseServerList) DeepCopy() *DatabaseServerList {
	if in == nil {
		return nil
	}
	out := new(DatabaseServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseServerNetworkSpec) DeepCopyInto(out *DatabaseServerNetworkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseServerNetworkSpec.
func (in *DatabaseServerNetworkSpec) DeepCopy() *DatabaseServerNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseServerNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseServerParameter) DeepCopyInto(out *DatabaseServerParameter) {
	*out = *in
	out.Value = in.Value
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseServerParameter.
func (in *DatabaseServerParameter) DeepCopy() *DatabaseServerParameter {
	if in == nil {
		return nil
	}
	out := new(DatabaseServerParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseServerParameterError) DeepCopyInto(out *DatabaseServerParameterError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseServerParameterError.
func (in *DatabaseServerParameterError) DeepCopy() *DatabaseServerParameterError {
	if in == nil {
		return nil
	}
	out := new(DatabaseServerParameterError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseServerReference) DeepCopyInto(out *DatabaseServerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseServerReference.
func (in *DatabaseServerReference) DeepCopy() *DatabaseServerReference {
	if in == nil {
		return nil
	}
	out := new(DatabaseServerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseServerSpec) DeepCopyInto(out *DatabaseServerSpec) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(DatabaseServerNetworkSpec)
		**out = **in
	}
	if in.EnableExtensions != nil {
		in, out := &in.EnableExtensions, &out.EnableExtensions
		*out = make([]DatabaseServerExtension, len(*in))
		copy(*out, *in)
	}
	if in.ServerParams != nil {
		in, out := &in.ServerParams, &out.ServerParams
		*out = make([]DatabaseServerParameter, len(*in))
		copy(*out, *in)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(DatabaseServerStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HighAvailabilityEnabled != nil {
		in, out := &in.HighAvailabilityEnabled, &out.HighAvailabilityEnabled
		*out = new(bool)
		**out = **in
	}
	if in.BackupRetentionDays != nil {
		in, out := &in.BackupRetentionDays, &out.BackupRetentionDays
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseServerSpec.
func (in *DatabaseServerSpec) DeepCopy() *DatabaseServerSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseServerStatus) DeepCopyInto(out *DatabaseServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServerParameterErrors != nil {
		in, out := &in.ServerParameterErrors, &out.ServerParameterErrors
		*out = make([]DatabaseServerParameterError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseServerStatus.
func (in *DatabaseServerStatus) DeepCopy() *DatabaseServerStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseServerStorageSpec) DeepCopyInto(out *DatabaseServerStorageSpec) {
	*out = *in
	if in.SizeGB != nil {
		in, out := &in.SizeGB, &out.SizeGB
		*out = new(int32)
		**out = **in
	}
	if in.Tier != nil {
		in, out := &in.Tier, &out.Tier
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseServerStorageSpec.
func (in *DatabaseServerStorageSpec) DeepCopy() *DatabaseServerStorageSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseServerStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	out.Server = in.Server
	out.Access = in.Access
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseSpec.
func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseStatus) DeepCopyInto(out *DatabaseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ValidationErrors != nil {
		in, out := &in.ValidationErrors, &out.ValidationErrors
		*out = make([]DatabaseValidationError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseStatus.
func (in *DatabaseStatus) DeepCopy() *DatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseValidationError) DeepCopyInto(out *DatabaseValidationError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseValidationError.
func (in *DatabaseValidationError) DeepCopy() *DatabaseValidationError {
	if in == nil {
		return nil
	}
	out := new(DatabaseValidationError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentitySource) DeepCopyInto(out *IdentitySource) {
	*out = *in
	if in.IdentityRef != nil {
		in, out := &in.IdentityRef, &out.IdentityRef
		*out = new(ApplicationIdentityRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentitySource.
func (in *IdentitySource) DeepCopy() *IdentitySource {
	if in == nil {
		return nil
	}
	out := new(IdentitySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserIdentitySpec) DeepCopyInto(out *UserIdentitySpec) {
	*out = *in
	in.Identity.DeepCopyInto(&out.Identity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserIdentitySpec.
func (in *UserIdentitySpec) DeepCopy() *UserIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(UserIdentitySpec)
	in.DeepCopyInto(out)
	return out
}
