name: Prepare Job for Pushing Flux OCI Artifacts to Azure Container Registry
description: Downloads flux cli and fetches credentials for the Azure Container Registry (ACR) to use with flux.

inputs:
  flux_version:
    description: "Version of flux to use"
    required: false
    # renovate: datasource=github-releases depName=flux-cli packageName=fluxcd/flux2 versioning=semver
    default: "2.6.4"
    type: string
  azure_app_id:
    description: "Azure application id used to authenticate to altinncr"
    required: true
  azure_subscription_id:
    description: "Azure subscription id used to authenticate to altinncr"
    required: true
  azure_tenant_id:
    description: "Azure tenant id used to authenticate to altinncr"
    required: true
  acr_name:
    description: "Name of the Azure Container Registry (ACR) to use"
    required: false
    default: "altinncr"
    type: string
    pattern: "^[a-zA-Z0-9-]{5,50}$"

runs:
  using: composite
  steps:
    - name: Setup flux
      uses: fluxcd/flux2/action@8454b02a32e48d775b9f563cb51fdcb1787b5b93 # v2.7.5
      with:
        version: ${{ inputs.flux_version }}
    - name: az login
      uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
      with:
        client-id: ${{ inputs.azure_app_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
