apiVersion: storage.dis.altinn.cloud/v1alpha1
kind: LogicalDatabase
metadata:
  name: router
  namespace: product-myproduct
spec:
  name: router
  server:
    name: myproduct-dev
  access:
    app:
      name: myproduct-router-dev
      principalId: "00000000-0000-0000-0000-000000000000"
    owner:
      name: my-team-db-owners
      principalId: "11111111-1111-1111-1111-111111111111"
  deletionPolicy: Retain
