# This rule is not used by the project dis-apim-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to apim.dis.altinn.cloud resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dis-apim-operator
    app.kubernetes.io/managed-by: kustomize
  name: api-viewer-role
rules:
- apiGroups:
  - apim.dis.altinn.cloud
  resources:
  - apis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apim.dis.altinn.cloud
  resources:
  - apis/status
  verbs:
  - get
