# This rule is not used by the project dis-apim-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apim.dis.altinn.cloud.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dis-apim-operator
    app.kubernetes.io/managed-by: kustomize
  name: backend-admin-role
rules:
- apiGroups:
  - apim.dis.altinn.cloud
  resources:
  - backends
  verbs:
  - '*'
- apiGroups:
  - apim.dis.altinn.cloud
  resources:
  - backends/status
  verbs:
  - get
