# permissions for end users to view backends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dis-apim-operator
    app.kubernetes.io/managed-by: kustomize
  name: backend-viewer-role
rules:
- apiGroups:
  - apim.dis.altinn.cloud
  resources:
  - backends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apim.dis.altinn.cloud
  resources:
  - backends/status
  verbs:
  - get
