# This rule is not used by the project dis-apim-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the apim.dis.altinn.cloud.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dis-apim-operator
    app.kubernetes.io/managed-by: kustomize
  name: backend-editor-role
rules:
- apiGroups:
  - apim.dis.altinn.cloud
  resources:
  - backends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apim.dis.altinn.cloud
  resources:
  - backends/status
  verbs:
  - get
