---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apim.dis.altinn.cloud
  resources:
  - apis
  - apiversions
  - backends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apim.dis.altinn.cloud
  resources:
  - apis/finalizers
  - apiversions/finalizers
  - backends/finalizers
  verbs:
  - update
- apiGroups:
  - apim.dis.altinn.cloud
  resources:
  - apis/status
  - apiversions/status
  - backends/status
  verbs:
  - get
  - patch
  - update
