project_name: daisctl

builds:
  - binary: dais
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/altinn/altinn-platform/daisctl/internal/version.version={{ .Version }}
      - -X github.com/altinn/altinn-platform/daisctl/internal/version.commit={{ .Commit }}
      - -X github.com/altinn/altinn-platform/daisctl/internal/version.date={{ .CommitDate }}


changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
    include:
      - cli
      - daisctl

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

source:
  enabled: false
  # name_template: '{{ .ProjectName }}-{{ .Version }}-source'
