apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      version: 1.17.1
  interval: 1h
  timeout: 5m
  install:
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    crds:
      enabled: true
    dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"
    dns01RecursiveNameserversOnly: true
    image:
      registry: altinncr.azurecr.io
    webhook:
      image:
        registry: altinncr.azurecr.io
    cainjector:
      image:
        registry: altinncr.azurecr.io
    acmesolver:
      image:
        registry: altinncr.azurecr.io
    startupapicheck:
      image:
        registry: altinncr.azurecr.io
