name: altinncr.azurecr.io deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'refs/heads/main')}}

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/altinncr-deploy.yml
      - actions/terraform/apply/**
      - actions/terraform/plan/**
      - infrastructure/adminservices-prod/altinncr/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/altinncr-deploy.yml
      - actions/terraform/apply/**
      - actions/terraform/plan/**
      - infrastructure/adminservices-prod/altinncr/**
  workflow_dispatch:
    inputs:
      log_level:
        required: true
        description: Terraform Log Level
        default: INFO
        type: choice
        options:
          - TRACE
          - DEBUG
          - INFO
          - WARN
          - ERROR

env:
  ENVIRONMENT: prod
  TF_STATE_NAME: altinncr.tfstate
  TF_PROJECT: ./infrastructure/adminservices-prod/altinncr
  ARM_CLIENT_ID: ${{ secrets.TF_AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: 1ce8e9af-c2d6-44e7-9c5e-099a308056fe

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  plan:
    name: Plan
    environment: reader
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Terraform Plan
        uses: Altinn/altinn-platform/actions/terraform/plan@92155c50cbf3083e20862d697c8b6b28316bf924 # main
        with:
          working_directory: ${{ env.TF_PROJECT }}
          oidc_type: environment
          oidc_value: ${{ env.ENVIRONMENT }}
          arm_client_id: ${{ env.ARM_CLIENT_ID }}
          arm_subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}
          tf_state_name: ${{ env.TF_STATE_NAME }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    environment: prod
    if: github.ref == 'refs/heads/main'
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Terraform Apply
        uses: Altinn/altinn-platform/actions/terraform/apply@92155c50cbf3083e20862d697c8b6b28316bf924 # main
        with:
          working_directory: ${{ env.TF_PROJECT }}
          oidc_type: environment
          oidc_value: ${{ env.ENVIRONMENT }}
          arm_client_id: ${{ env.ARM_CLIENT_ID }}
          arm_subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}
          tf_state_name: ${{ env.TF_STATE_NAME }}
