name: Release Daisctl

env:
  WORKDIR: tools/daisctl

on:
  push:
    tags:
      - "*-daisctl"

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache: true
      - uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          distribution: goreleaser
          version: 'latest'
          args: release --clean
          workdir: ${{ env.WORKDIR }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
