name: Release Daisctl

env:
  WORKDIR: tools/daisctl

on:
  push:
    tags:
      - "*-daisctl"

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache: true
      - uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6
        with:
          distribution: goreleaser
          version: 'latest'
          args: release --clean
          workdir: ${{ env.WORKDIR }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
