name: Daisctl PRs

env:
  WORKDIR: tools/daisctl

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - "tools/daisctl/**/*.go"
      - "tools/daisctl/go.*"
      - "tools/daisctl/Makefile"
      - "./github/workflows/daisctl-pr.yml"

jobs:
  tidy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache: true
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

  lint:
    needs: tidy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache: true
      - name: pwd
        run: pwd
      - name: lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: latest

  tests-windows:
    needs: lint
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache: true
      - name: Run tests
        run: make.exe test

  tests-macos:
    needs: lint
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache: true
      - name: Run tests
        run: make test

  tests-unix:
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache: true
      - name: Run tests
        run: make test

