name: Daisctl PRs

env:
  WORKDIR: tools/daisctl

on:
  push:
    branches:
      - "main"
    paths:
      - "tools/daisctl/**/*.go"
      - "tools/daisctl/go.*"
      - "tools/daisctl/Makefile"
      - ".github/workflows/daisctl-pr.yml"
  pull_request:
    paths:
      - "tools/daisctl/**/*.go"
      - "tools/daisctl/go.*"
      - "tools/daisctl/Makefile"
      - ".github/workflows/daisctl-pr.yml"

jobs:
  tidy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache: true
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

  lint:
    needs: tidy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache: true
      - name: lint
        uses: golangci/golangci-lint-action@4696ba8babb6127d732c3c6dde519db15edab9ea # v6.5.1
        with:
          version: latest
          working-directory: ${{ env.WORKDIR }}

  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            shell: bash
            test-cmd: make test
          - os: macos-latest
            shell: bash
            test-cmd: make test
          - os: windows-latest
            shell: powershell
            test-cmd: make.exe test
    name: Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache: true
      - name: Run tests
        run: ${{ matrix.test-cmd }}
