name: Dis Identity Lint and Test


on:
  push:
    branches:
      - main
    paths:
      - services/dis-identity-operator/**
      - .github/workflows/dis-identity-lint-test.yml
  pull_request:
    branches:
      - main
    paths:
      - services/dis-identity-operator/**
      - .github/workflows/dis-identity-lint-test.yml

permissions:
  contents: read

jobs:
  lint:
    name: Run linter on Ubuntu
    runs-on: self-hosted
    defaults:
      run:
        working-directory: services/dis-identity-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'services/dis-identity-operator/go.mod'
          cache-dependency-path: 'services/dis-identity-operator/go.sum'

      - name: Run linter
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.12.2
          working-directory: services/dis-identity-operator
  test:
    name: Run tests on Ubuntu
    runs-on: self-hosted
    defaults:
      run:
        working-directory: services/dis-identity-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'services/dis-identity-operator/go.mod'
          cache-dependency-path: 'services/dis-identity-operator/go.sum'

      - name: Running Tests
        run: |
          go mod tidy
          make test
