name: Dis APIM Operator Lint and Test

on:
  push:
    branches:
      - main
    paths:
      - services/dis-apim-operator/**
      - .github/workflows/dis-apim-lint-test.yml
  pull_request:
    branches:
      - main
    paths:
      - services/dis-apim-operator/**
      - .github/workflows/dis-apim-lint-test.yml

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint and Test on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/dis-apim-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'services/dis-apim-operator/go.mod'
          cache-dependency-path: 'services/dis-apim-operator/go.sum'

      - name: Run linter
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1.6
          working-directory: services/dis-apim-operator

      - name: Running Tests
        run: |
          go mod tidy
          make test
