name: Publish DIS Syncroot Artifact
run-name: Publish DIS syncroot to ${{ inputs.environment }}

env:
  SYNCROOT_ARTIFACT_NAME: dis/syncroot

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: choice
        required: true
        options:
          - at22
          - at23

permissions:
  contents: read
  id-token: write

concurrency:
  group: dis-syncroot-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  publish-syncroot:
    name: Publish syncroot artifact
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Validate syncroot image
        uses: Altinn/altinn-platform/actions/flux/verify-syncroot@e095eaa67ba630897e9b488a933c8ebb82b36732 # main
        with:
          workdir: ./deploy/common

      - name: Build and push syncroot artifact
        uses: Altinn/altinn-platform/actions/flux/build-push-image@e095eaa67ba630897e9b488a933c8ebb82b36732 # main
        with:
          image_name: ${{ env.SYNCROOT_ARTIFACT_NAME }}
          tag: ${{ inputs.environment }}
          workdir: ./deploy/common
          azure_subscription_id: ${{ secrets.DIS_SYNCROOT_AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.DIS_SYNCROOT_AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.DIS_SYNCROOT_AZURE_TENANT_ID }}
