name: Lint


on:
  push:
    branches:
      - main
    paths:
      - services/dis-identity-operator/**
      - .github/workflows/dis-identity-lint-test.yml
  pull_request:
    branches:
      - main
    paths:
      - services/dis-identity-operator/**
      - .github/workflows/dis-identity-lint-test.yml

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/dis-identity-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: 'services/dis-identity-operator/go.mod'
          cache-dependency-path: 'services/dis-identity-operator/go.sum'

      - name: Run linter
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1.6
          working-directory: services/dis-identity-operator
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/dis-identity-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: 'services/dis-identity-operator/go.mod'
          cache-dependency-path: 'services/dis-identity-operator/go.sum'

      - name: Running Tests
        run: |
          go mod tidy
          make test
