name: Dis-apim-operator Lint

on:
  push:
    branches:
      - main
    paths:
      - services/dis-apim-operator/**
      - .github/workflows/dis-apim-lint.yml
  pull_request:
    branches:
      - main
    paths:
      - services/dis-apim-operator/**
      - .github/workflows/dis-apim-lint.yml

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/dis-apim-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version-file: 'services/dis-apim-operator/go.mod'

      - name: Run linter
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # v6
        with:
          version: v1.64
          working-directory: services/dis-apim-operator
