name: Dis-apim-operator Tests

on:
  push:
    branches:
      - main
    paths:
      - services/dis-apim-operator/**
      - .github/workflows/dis-apim-test.yml
  pull_request:
    branches:
      - main
    paths:
      - services/dis-apim-operator/**
      - .github/workflows/dis-apim-test.yml

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/dis-apim-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: 'services/dis-apim-operator/go.mod'

      - name: Running Tests
        run: |
          go mod tidy
          make test
