name: Publish DIS Syncroot Artifact

env:
  SYNCROOT_ARTIFACT_NAME: dis/syncroot
  SYNCROOT_ENVIRONMENT: at22

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/dis-syncroot-release.yml
      - syncroot/**

permissions:
  contents: read
  id-token: write

jobs:
  publish-syncroot:
    name: Publish syncroot artifact
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: at22
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate syncroot image
        uses: Altinn/altinn-platform/actions/flux/verify-syncroot@ae178837969e98ccb088d8c8b64466a0e07cd565 # main
        with:
          workdir: ./syncroot

      - name: Build and push at22 syncroot artifact
        uses: Altinn/altinn-platform/actions/flux/build-push-image@ae178837969e98ccb088d8c8b64466a0e07cd565 # main
        with:
          image_name: ${{ env.SYNCROOT_ARTIFACT_NAME }}
          tag: ${{ env.SYNCROOT_ENVIRONMENT }}
          workdir: ./syncroot
          azure_subscription_id: ${{ secrets.DIS_SYNCROOT_AZURE_SUBSCRIPTION_ID }}
          azure_app_id: ${{ secrets.DIS_SYNCROOT_AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.DIS_SYNCROOT_AZURE_TENANT_ID }}
