name: Scan/Release Dis Apim Operator Image

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/dis-apim-release.yml
      - services/dis-apim-operator/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/dis-apim-release.yml
      - services/dis-apim-operator/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yml
    tags:
      - "dis-apim-*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-release:
    name: Build, scan and release
    uses: ./.github/workflows/reusable-image-scan-and-release-ghcr.yml
    with:
      release_latest: true
      tag_prefix: dis-apim-
      image_name: dis-apim-operator
      workdir: ./services/dis-apim-operator
