name: Dis Vault Lint and Test

on:
  push:
    branches:
      - main
    paths:
      - services/dis-vault-operator/**
      - .github/workflows/dis-vault-lint-test.yml
  pull_request:
    branches:
      - main
    paths:
      - services/dis-vault-operator/**
      - .github/workflows/dis-vault-lint-test.yml

permissions:
  contents: read

jobs:
  lint:
    name: Run linter on Ubuntu
    runs-on: self-hosted
    defaults:
      run:
        working-directory: services/dis-vault-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "services/dis-vault-operator/go.mod"
          cache-dependency-path: "services/dis-vault-operator/go.sum"

      - name: Run linter
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.12.2
          working-directory: services/dis-vault-operator
  test:
    name: Run tests on Ubuntu
    runs-on: self-hosted
    defaults:
      run:
        working-directory: services/dis-vault-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "services/dis-vault-operator/go.mod"
          cache-dependency-path: "services/dis-vault-operator/go.sum"

      - name: Running Tests
        run: |
          go mod tidy
          make test
