name: Dis Identity Lint and Test


on:
  push:
    branches:
      - main
    paths:
      - services/dis-identity-operator/**
      - .github/workflows/dis-identity-lint-test.yml
  pull_request:
    branches:
      - main
    paths:
      - services/dis-identity-operator/**
      - .github/workflows/dis-identity-lint-test.yml

permissions:
  contents: read

jobs:
  lint:
    name: Run linter on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/dis-identity-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'services/dis-identity-operator/go.mod'
          cache-dependency-path: 'services/dis-identity-operator/go.sum'

      - name: Run linter
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1.6
          working-directory: services/dis-identity-operator
  test:
    name: Run tests on Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/dis-identity-operator
    steps:
      - name: Clone the code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'services/dis-identity-operator/go.mod'
          cache-dependency-path: 'services/dis-identity-operator/go.sum'

      - name: Running Tests
        run: |
          go mod tidy
          make test
