name: Release Disctl

env:
  WORKDIR: tools/disctl

on:
  push:
    tags:
      - "*-disctl"

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache-dependency-path: '${{ env.WORKDIR }}/go.sum'
          cache: true
      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: 'latest'
          args: release --clean
          workdir: ${{ env.WORKDIR }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
