name: Release Disctl

env:
  WORKDIR: tools/disctl

on:
  push:
    tags:
      - "*-disctl"

permissions:
  contents: write
  id-token: write

jobs:
  goreleaser:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: '${{ env.WORKDIR }}/go.mod'
          cache-dependency-path: '${{ env.WORKDIR }}/go.sum'
          cache: true
      - uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
        with:
          distribution: goreleaser
          version: 'latest'
          args: release --clean
          workdir: ${{ env.WORKDIR }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
