name: Disctl PRs
permissions:
  contents: read

env:
  WORKDIR: tools/disctl

on:
  push:
    branches:
      - "main"
    paths:
      - "tools/disctl/**/*.go"
      - "tools/disctl/go.*"
      - "tools/disctl/Makefile"
      - ".github/workflows/disctl-pr.yml"
  pull_request:
    paths:
      - "tools/disctl/**/*.go"
      - "tools/disctl/go.*"
      - "tools/disctl/Makefile"
      - ".github/workflows/disctl-pr.yml"

jobs:
  tidy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "${{ env.WORKDIR }}/go.mod"
          cache-dependency-path: '${{ env.WORKDIR }}/go.sum'
          cache: true
      - name: Check go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

  lint:
    needs: tidy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "${{ env.WORKDIR }}/go.mod"
          cache-dependency-path: '${{ env.WORKDIR }}/go.sum'
          cache: true
      - name: lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.4.0
          working-directory: ${{ env.WORKDIR }}

  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            shell: bash
            test-cmd: make test
          - os: macos-latest
            shell: bash
            test-cmd: make test
          - os: windows-latest
            shell: powershell
            test-cmd: make.exe test
    name: Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "${{ env.WORKDIR }}/go.mod"
          cache-dependency-path: '${{ env.WORKDIR }}/go.sum'
          cache: true
      - name: Run tests
        run: ${{ matrix.test-cmd }}
