name: Scan/Release gh-runner base image

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/gh-runner-pr.yml
      - infrastructure/images/gh-runner/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yaml
  push:
    branches:
      - main
    paths:
      - .github/workflows/gh-runner-pr.yml
      - infrastructure/images/gh-runner/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yaml
    tags:
      - "ghrunner-*"

permissions:
  contents: read
  packages: write

jobs:
  scan:
    uses: ./.github/workflows/reusable-image-scan-and-release-ghcr.yaml
    with:
      release_latest: false
      image_name: gh-runner
      tag_prefix: ghrunner-
      workdir: ./infrastructure/images/gh-runner