name: Scan/Release gh-runner base Image

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/gh-runner-release.yml
      - infrastructure/images/gh-runner/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/gh-runner-release.yml
      - infrastructure/images/gh-runner/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yml
    tags:
      - "ghrunner-*"

permissions:
  contents: read
  packages: write

jobs:
  scan:
    uses: ./.github/workflows/reusable-image-scan-and-release-ghcr.yml
    with:
      release_latest: false
      image_name: gh-runner
      tag_prefix: ghrunner-
      workdir: ./infrastructure/images/gh-runner
