name: Test build gh-runner

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/gh-runner-pr.yml
      - infrastructure/images/gh-runner/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yaml

permissions:
  contents: read
  packages: read

jobs:
  scan:
    uses: ./.github/workflows/reusable-image-scan-and-release-ghcr.yaml
    with:
      release_latest: false
      image_name: gh-runner
      workdir: ./infrastructure/images/gh-runner