name: Vulncheck
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/govulncheck.yaml
      - "services/dis-apim-operator/**"
      - "services/dis-identity-operator/**"
      - "services/lakmus/**"
      - "tools/disctl/**"
      - "actions/generate-k6-manifests/**"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/govulncheck.yaml
      - "services/dis-apim-operator/**"
      - "services/dis-identity-operator/**"
      - "services/lakmus/**"
      - "tools/disctl/**"
      - "actions/generate-k6-manifests/**"
  schedule:
    - cron: "0 6 * * *" #Every day at 6

jobs:
  test-build:
    name: Check for go vulnerabilities
    runs-on: self-hosted
    continue-on-error: true
    strategy:
      matrix:
        module-dir:
          - "services/dis-apim-operator"
          - "services/dis-identity-operator"
          - "services/lakmus"
          - "tools/disctl"
          - "actions/generate-k6-manifests"
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - id: govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1.1.0
        with:
          go-version-file: go.mod
          repo-checkout: false
          work-dir: ${{ matrix.module-dir }}
