name: Test build K6 Action Image

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/k6-action-image-pr.yml
      - infrastructure/images/k6-action/**

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Git commit timestamps
        run: echo "TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./infrastructure/images/k6-action
          push: false
          load: true
          platforms: linux/amd64
          tags: k6-action-image:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
        env:
          SOURCE_DATE_EPOCH: ${{ env.TIMESTAMP }}
      - name: Scan with trivy
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: k6-action-image:test
          format: table
          exit-code: 1
          ignore-unfixed: true
          trivyignores: ./infrastructure/images/k6-action/.trivyignore
          vuln-type: os,library
          severity: HIGH,CRITICAL
