name: Scan/Release K6 Action Image

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/k6-action-image-release.yml
      - infrastructure/images/k6-action/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yml
    tags:
      - "k6-action-image-*"
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/k6-action-image-release.yml
      - infrastructure/images/k6-action/**
      - .github/workflows/reusable-image-scan-and-release-ghcr.yml
permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run tests
        shell: bash
        run: |
          cd actions/generate-k6-manifests && /usr/local/go/bin/go test -v ./...
  build-and-release:
    name: Build, scan and release
    uses: ./.github/workflows/reusable-image-scan-and-release-ghcr.yml
    with:
      release_latest: false
      image_name: k6-action-image
      tag_prefix: k6-action-image-
      workdir: ./infrastructure/images/k6-action
      platforms: linux/amd64
