name: Pack and publish NuGet packages

on:
  release:
    types:
      - published

jobs:
  build-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install deps
        run: |
          cd Altinn.Platform.Models/src
          dotnet restore
      - name: Build AccessTokenClient
        if: startsWith(github.ref, 'refs/tags/Altinn.Platform.Models-')
        run: |
          cd Altinn.Platform.Models/src
          dotnet build --configuration Release --no-restore -p:Deterministic=true -p:BuildNumber=${{ github.run_number }}          
      - name: Pack and publish AccessTokenClient
        if: startsWith(github.ref, 'refs/tags/Altinn.Platform.Models-')
        run: |
          cd Altinn.Platform.Models/src
          dotnet pack Altinn.Platform.Models.csproj --configuration Release --no-restore --no-build -p:BuildNumber=${{ github.run_number }} -p:Deterministic=true 