name: Pack and publish NuGet packages

on:
  release:
    types:
      - published

jobs:
  build-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install deps
        run: |
          cd Altinn.Platform.Models/src
          dotnet restore
      - name: Build Altinn.Platform.Models
        if: startsWith(github.ref, 'refs/tags/Altinn.Platform.Models-')
        run: |
          cd Altinn.Platform.Models/src
          dotnet build --configuration Release --no-restore -p:Deterministic=true -p:BuildNumber=${{ github.run_number }}
      - name: Pack and publish Altinn.Platform.Models
        if: startsWith(github.ref, 'refs/tags/Altinn.Platform.Models-')
        run: |
          cd Altinn.Platform.Models/src
          dotnet pack Altinn.Platform.Models.csproj --configuration Release --no-restore --no-build -p:BuildNumber=${{ github.run_number }} -p:Deterministic=true
          dotnet nuget push bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
