---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - application.dis.altinn.cloud
  resources:
  - applicationidentities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.azure.com
  resources:
  - roleassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authorization.azure.com
  resources:
  - roleassignments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - external-secrets.io
  resources:
  - secretstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - secretstores/status
  verbs:
  - get
- apiGroups:
  - keyvault.azure.com
  - vault.dis.altinn.cloud
  resources:
  - vaults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keyvault.azure.com
  - vault.dis.altinn.cloud
  resources:
  - vaults/status
  verbs:
  - get
  - patch
  - update
